# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pr:
- master
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  NAME: 'lychee'
  DOCKER_REPO: 'lycheeorg/lychee'
  OLD_DOCKER_REPO: 'lycheeorg/lychee-laravel'

stages:
- stage: build
  jobs:
  - job: build
    workspace:
      clean: all # ?
    steps:
      - bash: |
          curl -fsSL https://get.docker.com | sh
          echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
          mkdir -p $HOME/.docker
          echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
          sudo service docker start
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name xbuilder --use
          echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin
          echo "user: $REGISTRY_USER"
          echo "Building multi arch and pushing testing"
          TRAVIS_BUILD_STAGE_NAME="$AGENT_JOBNAME"
          if echo "$BUILD_SOURCEBRANCH" | grep "^refs/tags/" ; then TRAVIS_TAG="$BUILD_SOURCEBRANCH" ; fi
          TRAVIS_BRANCH=BUILD_SOURCEBRANCH
          if [ -z "$BUILD_REASON" = "PullRequest" ] ; then TRAVIS_PULL_REQUEST="false" ; fi
          echo "TRAVIS_BUILD_STAGE_NAME: $TRAVIS_BUILD_STAGE_NAME  AGENT_JOBNAME: $AGENT_JOBNAME  TRAVIS_BRANCH=BUILD_SOURCEBRANCH: $BUILD_SOURCEBRANCH"
          echo "TRAVIS_TAG: $TRAVIS_TAG  SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER  TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
          source ./deploy.sh
        env:
          REGISTRY_USER: $(registry_user)
          REGISTRY_PASS: $(registry_pass)
